### ISSUE TITLE
add Dependabot  GitHub Actions support

### ISSUE THREAD

**Issue by softwaredevelop** [softwaredevelop/container-latex#17]
add [Dependabot](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/keeping-your-actions-up-to-date-with-dependabot) [GitHub Actions support](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#package-ecosystem)

add the `.github/dependabot.yml` file:
```yaml
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```
